#!/usr/bin/env python3
"""
Synthetic PDK viability gate for VOID.

Consumes artifacts generated by:
  VoidAlchmey/tools/generate_synthetic_pdk.py

Gate intent:
- enforce constitutional alignment (no silicon/no copper/l3 immutability/dark-channel)
- enforce a minimum viability score threshold
- ensure living-system policy + KPI targets are present for funding-grade evidence
"""

from __future__ import annotations

import json
import os
from pathlib import Path


def env_float(name: str, default: float) -> float:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def env_flag(name: str, default: str = "0") -> bool:
    return os.environ.get(name, default).strip().lower() in {"1", "true", "yes", "on"}


def main() -> int:
    root = Path(__file__).resolve().parent
    repo_root = root.parent
    generated_root = repo_root / "pdk" / "synthetic_v1" / "generated"

    summary_path = generated_root / "synthetic_evidence_summary.json"
    manifest_path = generated_root / "synthetic_candidate_manifest.json"
    bom_path = generated_root / "XENALCHEMY_Synthetic_Candidate_BOM.csv"

    failures: list[str] = []

    if not summary_path.exists():
        failures.append(f"missing summary artifact: {summary_path}")
    if not manifest_path.exists():
        failures.append(f"missing manifest artifact: {manifest_path}")
    if not bom_path.exists():
        failures.append(f"missing candidate BOM artifact: {bom_path}")

    payload: dict = {}
    if not failures:
        payload = json.loads(summary_path.read_text(encoding="utf-8"))

        metrics = payload.get("metrics", {})
        constitutional = payload.get("constitutional", {})
        living_policy = payload.get("living_system_policy", {})
        kpi_targets = payload.get("kpi_targets", {})

        viability_score = float(metrics.get("viability_score", 0.0))
        threshold_from_summary = float(metrics.get("viability_threshold", 0.72))
        headroom = float(metrics.get("viability_headroom", viability_score - threshold_from_summary))
        headroom_target_from_summary = float(metrics.get("viability_headroom_target", 0.08))
        threshold_override = env_float("XENALCHEMY_SPDK_MIN_SCORE", threshold_from_summary)
        headroom_override = env_float("XENALCHEMY_SPDK_MIN_HEADROOM", headroom_target_from_summary)
        threshold = max(threshold_from_summary, threshold_override)
        headroom_target = max(headroom_target_from_summary, headroom_override)

        if not constitutional.get("pass", False):
            failures.append("constitutional alignment check failed")
        if viability_score < threshold:
            failures.append(
                f"viability_score {viability_score:.4f} below threshold {threshold:.4f}"
            )
        if headroom < headroom_target:
            failures.append(
                f"viability_headroom {headroom:.4f} below target {headroom_target:.4f}"
            )

        sensing = living_policy.get("sensing", {}) if isinstance(living_policy, dict) else {}
        required_signals = sensing.get("required_signals", [])
        if not isinstance(required_signals, list) or len(required_signals) < 4:
            failures.append("living-system sensing policy incomplete (<4 required signals)")

        if not isinstance(kpi_targets, dict) or not kpi_targets:
            failures.append("KPI targets missing from synthetic evidence")

        strict_living = env_flag("XENALCHEMY_REQUIRE_LIVING_POLICY", "1")
        if strict_living:
            homeostasis = living_policy.get("homeostasis", {})
            immune = living_policy.get("immune_response", {})
            regen = living_policy.get("regeneration", {})
            if not (isinstance(homeostasis, dict) and homeostasis.get("enabled", False)):
                failures.append("homeostasis policy missing or disabled")
            if not (isinstance(immune, dict) and immune.get("enabled", False)):
                failures.append("immune response policy missing or disabled")
            if not (isinstance(regen, dict) and regen.get("enabled", False)):
                failures.append("regeneration policy missing or disabled")

    report = {
        "summary_path": str(summary_path),
        "manifest_path": str(manifest_path),
        "bom_path": str(bom_path),
        "failures": failures,
        "pass": len(failures) == 0,
    }

    out_path = root / "synthetic_pdk_report.json"
    out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print("[synthetic_pdk_gate] pass:", report["pass"])
    print("[synthetic_pdk_gate] failures:", len(failures))
    if failures:
        for item in failures:
            print("[synthetic_pdk_gate] fail:", item)
    print("[synthetic_pdk_gate] report:", out_path)

    return 0 if report["pass"] else 6


if __name__ == "__main__":
    raise SystemExit(main())
