"""
Verify VoidOS Modules Generated by Truth AI
===========================================
Compiles the generated mailbox, scheduler, and treasury Logos intents,
loads them into the LogosVM, and simulates real-world execution scenarios.
"""

import os
import sys
import json

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from logos import compile_logos, LogosVM

def print_banner(text):
    print("=" * 80)
    print(f"  {text}")
    print("=" * 80)

def main():
    print_banner("VERIFYING VOIDOS MODULES GENERATED BY TRUTH AI")
    
    workspace = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    voidos_dir = os.path.join(workspace, "voidos")
    
    # ----------------------------------------------------
    # 1. VERIFY MAILBOX MODULE
    # ----------------------------------------------------
    print_banner("1. Simulating Mailbox Intent")
    mailbox_path = os.path.join(voidos_dir, "mailbox.logos")
    with open(mailbox_path, "r", encoding="utf-8") as f:
        mailbox_code = f.read()
        
    mesh = {
        "mass": 1000.0,
        "energy": 3600000.0,  # 1 kWh = 3.6e6 J
        "entropy": 10.0,
        "cycle": 1000.0
    }
    
    # Compile
    mailbox_smir = compile_logos(mailbox_code, mesh, mailbox_path)
    print("[COMPILE] Mailbox intent compiled successfully.")
    
    # VM init (initial requirement is 50 Wh = 180,000 J)
    vm_mesh = dict(mesh)
    vm = LogosVM(mailbox_smir, vm_mesh, {"replayed": 0, "is_valid_sig": 1})
    print(f"Initial State: {vm.current_state('Mailbox')}")
    assert vm.current_state('Mailbox') == 'Idle'
    
    # Test case A: Replayed envelope (replayed=1)
    # Action consumes 1 Wh = 3600 J. State remains Idle.
    vm.runtime_ctx["replayed"] = 1
    res = vm.send_event("Mailbox", "receive_envelope")
    print(f"Case A (replayed=1): {res['from']} --(receive_envelope)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Idle'
    
    # Test case B: Valid signature, not replayed (replayed=0, is_valid_sig=1)
    # Action consumes 0.1 Wh = 360 J. State transitions to Processing.
    vm.runtime_ctx["replayed"] = 0
    vm.runtime_ctx["is_valid_sig"] = 1
    res = vm.send_event("Mailbox", "receive_envelope")
    print(f"Case B (valid signature): {res['from']} --(receive_envelope)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Processing'
    
    # Test case C: Transition on 'done' to Idle
    res = vm.send_event("Mailbox", "done")
    print(f"Case C (done): {res['from']} --(done)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Idle'
    
    # Test case D: Invalid signature, not replayed (replayed=0, is_valid_sig=0)
    # Action consumes 0.5 Wh = 1800 J. State remains Idle.
    vm.runtime_ctx["replayed"] = 0
    vm.runtime_ctx["is_valid_sig"] = 0
    res = vm.send_event("Mailbox", "receive_envelope")
    print(f"Case D (invalid signature): {res['from']} --(receive_envelope)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Idle'
    
    # ----------------------------------------------------
    # 2. VERIFY SCHEDULER MODULE
    # ----------------------------------------------------
    print_banner("2. Simulating Scheduler Intent")
    scheduler_path = os.path.join(voidos_dir, "scheduler.logos")
    with open(scheduler_path, "r", encoding="utf-8") as f:
        scheduler_code = f.read()
        
    scheduler_smir = compile_logos(scheduler_code, mesh, scheduler_path)
    print("[COMPILE] Scheduler intent compiled successfully.")
    
    vm_mesh = dict(mesh)
    vm = LogosVM(scheduler_smir, vm_mesh, {"priority": 3})
    print(f"Initial State: {vm.current_state('Scheduler')}")
    assert vm.current_state('Scheduler') == 'Idle'
    
    # Test case A: Dispatch high priority task (priority = 3 > 2)
    # Requires 2 Wh = 7200 J. Transition to Running.
    res = vm.send_event("Scheduler", "dispatch_task")
    print(f"Case A (high priority): {res['from']} --(dispatch_task)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Running'
    
    # Complete task
    res = vm.send_event("Scheduler", "complete")
    assert res['to'] == 'Idle'
    
    # Test case B: Dispatch low priority task (priority = 1 <= 2)
    # Requires 0.5 Wh = 1800 J. Transition to Running.
    vm.runtime_ctx["priority"] = 1
    res = vm.send_event("Scheduler", "dispatch_task")
    print(f"Case B (low priority): {res['from']} --(dispatch_task)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Running'
    
    # ----------------------------------------------------
    # 3. VERIFY TREASURY MODULE
    # ----------------------------------------------------
    print_banner("3. Simulating Treasury Intent")
    treasury_path = os.path.join(voidos_dir, "treasury.logos")
    with open(treasury_path, "r", encoding="utf-8") as f:
        treasury_code = f.read()
        
    treasury_smir = compile_logos(treasury_code, mesh, treasury_path)
    print("[COMPILE] Treasury intent compiled successfully.")
    
    vm_mesh = dict(mesh)
    vm = LogosVM(treasury_smir, vm_mesh, {"is_inter_subnet": 1})
    print(f"Initial State: {vm.current_state('Treasury')}")
    assert vm.current_state('Treasury') == 'Idle'
    
    # Test case A: Process payment (inter-subnet = 1)
    # Requires 6.18 Wh = 22,248 J. Transition to Settled.
    res = vm.send_event("Treasury", "process_payment")
    print(f"Case A (inter-subnet): {res['from']} --(process_payment)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Settled'
    
    # Reset
    res = vm.send_event("Treasury", "reset")
    assert res['to'] == 'Idle'
    
    # Test case B: Process payment (inter-subnet = 0)
    # Requires 1.618 Wh = 5824.8 J. Transition to Settled.
    vm.runtime_ctx["is_inter_subnet"] = 0
    res = vm.send_event("Treasury", "process_payment")
    print(f"Case B (intra-subnet): {res['from']} --(process_payment)--> {res['to']} [{res['status']}]")
    assert res['status'] == 'transitioned'
    assert res['to'] == 'Settled'
    
    print_banner("ALL VOIDOS MODULE SIMULATIONS PASSED SUCCESSFULLY!")

if __name__ == "__main__":
    main()
